runner_delay = 180 # post update interval in secs in case of runner usage

source_order = [
  "twitch",
  "vk",
  "trovo",
] # info will be fetch from the first valid source

[target.telegram]
template = """🔴 live

<b>{title}</b>

Category: {category}
Duration: {duration}

👤 {viewers}"""
button = "WATCH STREAM"

[target.discord]
template = """{
  "url": "{url}",
  "author": { "name": "🔴 live" },
  "title": "{title}",
  "fields": [
    { "name": "Category", "value": "{category}"},
    { "name": "Duration", "value": "{duration}"}
  ],
  "footer": { "text": "👤 {viewers}"},
  "image": { "url": "{preview}" }
}"""
